spring:
  data:
    redis:
      password: ${REDIS_PASSWORD}

  mail:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: WARN
    com.travelit.backend: INFO
